/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meetle.gui;

import meetle.Meetle;
import meetle.utenti.Notifica;

/**
 *
 * @author Alessandro
 */
public class NotificaPanel extends javax.swing.JPanel {
    private int IDEvento;
    private int IDNotifica;

   public NotificaPanel(Notifica notifica) {
        initComponents();
        IDEvento = notifica.getEventoID();
        IDNotifica = notifica.getID();
        
        jLabelTestoNotifica.setText(notifica.getMessaggio());
        jLabelOrario.setText("Ora: " + notifica.getDataora().toString());
        if(notifica.isVisualizzata()) {
            jButtonSegnaLetto.setText("visualizzata");
            jButtonSegnaLetto.setEnabled(false);
        } else { jButtonSegnaLetto.setText("Segna come già letto"); }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTestoNotifica = new javax.swing.JLabel();
        jLabelOrario = new javax.swing.JLabel();
        jButtonVaiEvento = new javax.swing.JButton();
        jButtonSegnaLetto = new javax.swing.JButton();
        jButtonElimina = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 150, 155));

        jLabelTestoNotifica.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTestoNotifica.setText("Testo notifica");

        jLabelOrario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOrario.setText("Data e ora");

        jButtonVaiEvento.setText("Vai a evento");
        jButtonVaiEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVaiEventoActionPerformed(evt);
            }
        });

        jButtonSegnaLetto.setText("Segna come già letto");
        jButtonSegnaLetto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSegnaLettoActionPerformed(evt);
            }
        });

        jButtonElimina.setText("Elimina");
        jButtonElimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTestoNotifica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelOrario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonVaiEvento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSegnaLetto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonElimina)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonElimina)
                    .addComponent(jButtonSegnaLetto)
                    .addComponent(jButtonVaiEvento)
                    .addComponent(jLabelTestoNotifica)
                    .addComponent(jLabelOrario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVaiEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVaiEventoActionPerformed
        java.awt.EventQueue.invokeLater(() -> { new EventoFrame(IDEvento, EventoFrame.VISUALIZZA).setVisible(true); });
    }//GEN-LAST:event_jButtonVaiEventoActionPerformed

    private void jButtonSegnaLettoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSegnaLettoActionPerformed
        Meetle.getIstanza().setNotificaLetta(Meetle.getIstanza().getUtenteLoggatoID(), IDNotifica);
    }//GEN-LAST:event_jButtonSegnaLettoActionPerformed

    private void jButtonEliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminaActionPerformed
        Meetle.getIstanza().rimuoviNotifica(Meetle.getIstanza().getUtenteLoggatoID(), IDNotifica);
    }//GEN-LAST:event_jButtonEliminaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonElimina;
    private javax.swing.JButton jButtonSegnaLetto;
    private javax.swing.JButton jButtonVaiEvento;
    private javax.swing.JLabel jLabelOrario;
    private javax.swing.JLabel jLabelTestoNotifica;
    // End of variables declaration//GEN-END:variables
}
