/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meetle.gui;

import meetle.Meetle;
import meetle.utenti.Notifica;

/**
 *
 * @author Alessandro
 */
public class NotificaPanel extends javax.swing.JPanel {
    private int IDEvento;
    private int IDNotifica;
    private Meetle meetle;

   public NotificaPanel(Meetle meetle, Notifica notifica) {
        initComponents();
        this.meetle = meetle;
        IDEvento = notifica.getEventoID();
        IDNotifica = notifica.getID();
        
        testoNotificaLabel.setText(notifica.getMessaggio());
        orarioLabel.setText("Ora: " + notifica.getDataora().toString());
        if(notifica.isVisualizzata()) {
            lettoButton.setText("visualizzata");
            lettoButton.setEnabled(false);
        } else { lettoButton.setText("Segna come già letto"); }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        testoNotificaLabel = new javax.swing.JLabel();
        eliminaButton = new javax.swing.JButton();
        lettoButton = new javax.swing.JButton();
        orarioLabel = new javax.swing.JLabel();
        eventoButton = new javax.swing.JButton();

        testoNotificaLabel.setText("Testo notifica");

        eliminaButton.setText("Elimina");
        eliminaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminaButtonActionPerformed(evt);
            }
        });

        lettoButton.setText("Segna come già letto");
        lettoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lettoButtonActionPerformed(evt);
            }
        });

        orarioLabel.setText("Data e ora");

        eventoButton.setText("Vai a evento");
        eventoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(testoNotificaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(orarioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eventoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lettoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminaButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(testoNotificaLabel)
                    .addComponent(eliminaButton)
                    .addComponent(lettoButton)
                    .addComponent(orarioLabel)
                    .addComponent(eventoButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void eventoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventoButtonActionPerformed
        java.awt.EventQueue.invokeLater(() -> { new EventoFrame(meetle, meetle.getBacheca().getByID(IDEvento), EventoFrame.VISUALIZZA).setVisible(true); });
    }//GEN-LAST:event_eventoButtonActionPerformed

    private void lettoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lettoButtonActionPerformed
        meetle.setNotificaLetta(meetle.getUtenteLoggatoID(), IDNotifica);
    }//GEN-LAST:event_lettoButtonActionPerformed

    private void eliminaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminaButtonActionPerformed
        meetle.rimuoviNotifica(meetle.getUtenteLoggatoID(), IDNotifica);
    }//GEN-LAST:event_eliminaButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eliminaButton;
    private javax.swing.JButton eventoButton;
    private javax.swing.JButton lettoButton;
    private javax.swing.JLabel orarioLabel;
    private javax.swing.JLabel testoNotificaLabel;
    // End of variables declaration//GEN-END:variables
}
